import os
import json, jsonlines
import argparse
import torch
from tqdm import tqdm
from packaging.version import parse
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import warnings
warnings.filterwarnings('ignore')
from transformers import logging
logging.set_verbosity_error()

VERILOG_ONLY_PROMPT = '''You only complete chats with correct and concise detailed global summary of the given Verilog code in English. You first summarize overall functionality in a paragraph, then describe parameters in a paragraph without listing, next you list key input signals each with one sentence of explanation, finally you list key output signals each with one sentence of explanation. Do not list input signals if there are too many. Do not list output signals if there are too many.

Try to cover these relevant perspectives if needed:

    Functionality: What the code does and its purpose.
    Inputs/Outputs: The role of inputs, outputs, and how they affect the circuit.
    Registers/Wires: Identify and explain the purpose of any registers or wires.
    Control Flow: Key decision-making structures (e.g., if, case), and whether the design is combinational or sequential.
    Clock/Reset: Explain how clock and reset signals control the circuit's operation.
    Final Output: How the final output is computed from the inputs and internal logic.

You summarize up to sufficient details such that Verilog engineers can implement the given Verilog code based on your summary.  Provide a clear, concise, and sufficient summary, focusing on how the design works and what it's meant to achieve. Try to make sure that the produced summary is less than 1000 words. Don't include irrelevant information like testbench. Provide a quick answer without overthinking. Please directly write your summary without any titles or other extra formats.

Here is the Verilog code:

'''

VERILOG_AND_VERILATOR_CPP_PROMPT_PART_1_OF_2 = '''Given the following code of a Verilog module and this module's CPP code genearted from Verilator, please summarize the functionality of the Verilog code.

Here is the module's CPP code from verilator:

'''
VERILOG_AND_VERILATOR_CPP_PROMPT_PART_2_OF_2 = '''

You only complete chat with correct and concise detailed global summary of the given Verilog code in English. You first summarize overall functionality in a paragraph, then describe parameters in a paragraph without listing, next you list key input signals each with one sentence of explanation, finally you list key output signals each with one sentence of explanation. Do not list input signals if there are too many. Do not list output signals if there are too many.

Try to cover these relevant perspectives if needed:

    Functionality: What the code does and its purpose.
    Inputs/Outputs: The role of inputs, outputs, and how they affect the circuit.
    Registers/Wires: Identify and explain the purpose of any registers or wires.
    Control Flow: Key decision-making structures (e.g., if, case), and whether the design is combinational or sequential.
    Clock/Reset: Explain how clock and reset signals control the circuit's operation.
    Final Output: How the final output is computed from the inputs and internal logic.

You only summarize Verilog code below, do not summarize CPP code above. You summarize up to sufficient details of the Verilog code such that Verilog engineers can implement the given Verilog code based on your summary. Provide a clear, concise, and sufficient summary, focusing on how the design works and what it's meant to achieve. Try to make sure that the produced summary is less than 1000 words. Don't include irrelevant information like testbench or hardware design simulation. Provide a quick answer without overthinking. Please directly write your summary without any titles or other extra formats. The CPP code from Verilator above describes the same Verilog module as below, but it is only used for your reference. The CPP code above should not be included in your summary, just use it to understand code functionality where you don't understand the Verilog code. Do not summarize any CPP functions or code above.

Here is the Verilog module code:

'''

VERILOG_AND_VITIS_CPP_PROMPT_PART_1_OF_3 = '''Given the following C++ code and the Verilog code generated from C++ code using Vitis HLS, please summarize the functionality of the Verilog code.

Here is the Verilog module code generated by Vitis HLS:

'''
VERILOG_AND_VITIS_CPP_PROMPT_PART_2_OF_3 = '''

Here is the C++ code:

'''
VERILOG_AND_VITIS_CPP_PROMPT_PART_3_OF_3 = '''

You only complete chat with correct and concise detailed global summary of the given Verilog code in English. You first summarize overall functionality only in a short paragraph, then describe parameters only in a short paragraph without listing, next you list key input signals each with one sentence of explanation, finally you list key output signals each with one sentence of explanation. Do not list input signals if there are too many. Do not list output signals if there are too many.

Try to cover these relevant perspectives if needed:

    Functionality: What the code does and its purpose.
    Inputs/Outputs: The role of inputs, outputs, and how they affect the circuit.
    Registers/Wires: Identify and explain the purpose of any registers or wires.
    Control Flow: Key decision-making structures (e.g., if, case), and whether the design is combinational or sequential.
    Clock/Reset: Explain how clock and reset signals control the circuit's operation.
    Final Output: How the final output is computed from the inputs and internal logic.

You only summarize Verilog code above, do not summarize C++ code above. You summarize up to sufficient details of the Verilog code such that Verilog engineers can implement the given Verilog code based on your summary. Provide a clear, concise, and sufficient summary, focusing on how the design works and what it's meant to achieve. Try to make sure that the produced summary is less than 1000 words. You only include descriptions that you feel certainly correct, do not use "seems to be", "appears to be", "likely", "looks like", or similar words in your descriptions. If you are not sure about functionality then choose one possiblity and provide a solid description. Don't provided descriptions on how to improve the module. Don't describe how to verify correct functionality of the module. Don't include irrelevant information like testbench or hardware design simulation. Please directly write your summary without any titles or other extra formats. Don't write a conclusion. The Vitis HLS C++ code above describes the same Verilog module as above, but it is only used for your reference. The C++ code above should not be included in your summary, just use it to understand code functionality where you don't understand the Verilog code. Do not summarize any C++ functions or code above.'''

VALID_PROMPT_TYPES = ['VERILOG_ONLY', "VERILOG_AND_VERILATOR", "VERILOG_AND_VITIS_CPP"]
REQUIRED_SAMPLE_KEYS  = ["code", "full_code", "index", "cpp_code"] 


def load_json(file_name):
    with open(file_name, 'r') as json_file:
        return json.load(json_file)
    
def load_jsonl(file_name):
    data = []
    with jsonlines.open(file_name) as reader:
        for obj in reader:
            data.append(obj)
    return data

def generate_prompt(sample, sample_type):
    assert sample_type in VALID_PROMPT_TYPES, print("ERROR:", sample_type, "not in", VALID_PROMPT_TYPES)
    if sample_type  == "VERILOG_ONLY":
        return VERILOG_ONLY_PROMPT + sample['full_code']
    elif sample_type == "VERILOG_AND_VERILATOR":
        return VERILOG_AND_VERILATOR_CPP_PROMPT_PART_1_OF_2 + sample['cpp_code'] + VERILOG_AND_VERILATOR_CPP_PROMPT_PART_2_OF_2 + sample['full_code']
    else:
        return VERILOG_AND_VITIS_CPP_PROMPT_PART_1_OF_3 + sample['full_code'] + VERILOG_AND_VITIS_CPP_PROMPT_PART_2_OF_3 + sample['cpp_code'] + VERILOG_AND_VITIS_CPP_PROMPT_PART_3_OF_3

def send_prompt_to_ollama(input_text, tokenizer, model, max_new_tokens, max_input_length=40*1024):
    input_text = tokenizer.apply_chat_template( [{"role": "user", "content": input_text+"\n"}], 
                    tokenize=False, add_generation_prompt=True  )
    input_ids = tokenizer(input_text, return_tensors='pt').input_ids.to(model.device)
    if input_ids.shape[1] > max_input_length:
        return ""
    #     print(f"Warning: Input length ({input_ids.shape[1]}) exceeds max_input_length ({max_input_length}). Truncating input.")
    #     input_ids = input_ids[:, :max_input_length]
    assert input_ids.shape[1] <= max_input_length
    output_ids = model.generate(input_ids, max_new_tokens=max_new_tokens)
    generated_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    assert "</think>" in generated_text
    return generated_text


def process_and_save_batch(batch, batch_num, save_path, tokenizer, model, max_new_tokens, prompt_type):
    """Process a batch of modules one by one, and save the results evey batch_num samples in JSONL format."""
    output_data = []
    for idx, result in tqdm(enumerate(batch), total=len(batch), desc=f"Processing batch {batch_num}", leave=False):
        for k in REQUIRED_SAMPLE_KEYS:
            assert k in result.keys(), print("ERROR: sample does not contain required key:", k)
        input_sample_idx = result['index']
        verilog_code = result['full_code']
        verilog_code_woio = result['code']
        ioheader = verilog_code.replace(verilog_code_woio, "")
        input_text = generate_prompt(sample=result, sample_type=prompt_type)
        response = send_prompt_to_ollama(input_text, tokenizer=tokenizer, model=model, max_new_tokens=max_new_tokens)
        output_data.append({
            'index': input_sample_idx,
            'verilog_code': verilog_code_woio,
            'full_code': verilog_code,
            'ioheader': ioheader,
            'conversation': response,
        })
    with jsonlines.open(save_path, 'a') as f:
        f.write_all(output_data)


def process_file(file_path, save_path, tokenizer, model, start_idx, end_idx, prompt_type, batch_size=1, max_new_tokens=8192):
    """Process the JSON file in batches and save results."""
    # calculate batch runtime metrics, convert end_idx from inclusive to exclusive
    inputs = load_jsonl(file_path)
    end_idx = min(end_idx+1, len(inputs))
    total_batches = (end_idx - start_idx) // batch_size
    # calculate where to resume labeling or start from idx 0
    finished_num_samples = 0
    if os.path.isfile(save_path):
        finished_num_samples = len(load_jsonl(save_path))
    # loop and process batches
    for i in tqdm(range(start_idx, end_idx, batch_size), total=total_batches, desc="Processing batches"):
        batch = inputs[i:min(end_idx,i+batch_size)]
        batch_num = i // batch_size
        if i+batch_size < start_idx+finished_num_samples:
            continue
        elif i < start_idx+finished_num_samples:
            batch = inputs[start_idx+finished_num_samples:min(end_idx,i+batch_size)]
        process_and_save_batch(batch=batch, batch_num=batch_num, save_path=save_path, tokenizer=tokenizer, model=model, max_new_tokens=max_new_tokens, prompt_type=prompt_type)

def extract_module_declaration(verilog_code):
    """Extract the module declaration from Verilog code."""
    pattern = r'module\s+(\w+)\s*\(([\s\S]*?)\);'
    match = re.search(pattern, verilog_code)
    if match:
        return f"module {match.group(1)}({match.group(2)});"
    raise RuntimeError()
    

def parse_args():
    parser = argparse.ArgumentParser(description="Process Verilog files using a range of entries.")
    parser.add_argument('--start_idx', type=int, default=0, help='Starting index for processing.')
    parser.add_argument('--end_idx', type=int, default=2, help='Ending index for processing, inclusive.')
    parser.add_argument('--src_path', type=str, default="", help='Absolute path of the file that contains source dataset to be labeled.')
    parser.add_argument('--save_path', type=str, default="", help='Absolute path of the file that saves all inference results.')
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    checkpoint_dir = "/projects/bcct/llm_models/deepseek-r1-70b-hf"
    assert args.src_path != ""
    assert args.save_path != ""
    file_path = args.src_path
    save_path = args.save_path
    max_new_tokens = 8192
    prompt_type = "VERILOG_AND_VERILATOR"
    batch_size = 1  # batch is not for parallel inferencing but for failure recovery: save to disk every batch_size samples.
    bf16 = True
    fp16 = False

    if torch.cuda.is_available():
        n_gpus = torch.cuda.device_count()
    max_memory = f'{38 * 1024}MB'
    max_memory = {i: max_memory for i in range(n_gpus)}
    # device_map = "auto"
    device_map = "balanced"
    if os.environ.get('LOCAL_RANK') is not None:
        local_rank = int(os.environ.get('LOCAL_RANK', '0'))
        print("distributed", local_rank)
        device_map = {'': local_rank}
        max_memory = {'': max_memory[local_rank]}
    model = AutoModelForCausalLM.from_pretrained(
        checkpoint_dir,
        device_map=device_map,
        max_memory= max_memory,
        quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            # load_in_8bit=False,
            # llm_int8_threshold=6.0,
            # llm_int8_has_fp16_weight=False,
            # bnb_4bit_use_double_quant=True,
            # bnb_4bit_quant_type="nf4",
        ),
        torch_dtype=(torch.float32 if fp16 else (torch.bfloat16 if bf16 else torch.float32)),
    )
    print("LLM loaded on device(s):", model.device)
    tokenizer = AutoTokenizer.from_pretrained(checkpoint_dir)

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    print(f"\nProcessing '{file_path}'...")
    process_file(file_path=file_path, save_path=save_path, tokenizer=tokenizer, model=model, start_idx=args.start_idx, end_idx=args.end_idx, batch_size=batch_size, prompt_type=prompt_type, max_new_tokens=max_new_tokens)
    